vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
vim.keymap.set('n', '<leader>l', '<cmd>Augment chat-toggle<CR>', { desc = 'Toggle chat window' })
vim.keymap.set('n', '<C-s>', '<cmd>w<CR>', { desc = 'Save on control s' })
vim.keymap.set('n', '<C-q>', '<cmd>q<CR>', { desc = 'Quit window' })
vim.keymap.set('n', '<Tab>', ':bnext<CR>', { desc = 'Next buffer' })
vim.keymap.set('n', '<S-Tab>', ':bprevious<CR>', { desc = 'Last buffer' })
vim.keymap.set('n', '<leader>x', ':bdelete!<CR>', { desc = 'Close buffer' })
vim.keymap.set('n', '<leader>n', '<cmd> enew <CR>', { desc = 'New buffer' })
vim.keymap.set('v', '<A-j>', ':m .+1<CR>==', { desc = 'Move selection down' })
vim.keymap.set('v', '<A-k>', ':m .-2<CR>==', { desc = 'Move selection up' })
