#!/bin/sh

system_type=$(uname -s)

if [ -x "$(command -v nvim)" ]; then
  echo "neovim is already installed"
else
  echo "neovim is not installed"
  if [ "$system_type" = "Darwin" ]; then
    brew install neovim
  else
    if [ -x "$(command -v pacman)" ]; then
      sudo pacman -S neovim --noconfirm
    else
      curl -LO https://github.com/neovim/neovim-releases/releases/latest/download/nvim-linux-x86_64.tar.gz
      sudo rm -rf /opt/nvim
      sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
      sudo ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/bin/nvim
      rm nvim-linux-x86_64.tar.gz
    fi
  fi
  git config --global core.editor nvim
fi

if [ -x "$(command -v starship)" ]; then
  echo "starship is already installed"
else
  echo "starship is not installed"
  curl -sS https://starship.rs/install.sh | sh -s -- -y
  echo 'eval "$(starship init bash)"' >> ~/.bashrc
  echo 'eval "$(starship init zsh)"' >> ~/.zshrc
fi

if [ -x "$(command -v fzf)" ]; then
  echo "fzf is already installed"
else
  echo "fzf is not installed"
  if [ "$system_type" = "Darwin" ]; then
    brew install fzf
  else
    if [ -x "$(command -v pacman)" ]; then
      sudo pacman -S fzf --noconfirm
    else
      sudo apt install fzf -y
    fi
  fi
fi

if [ -x "$(command -v rg)" ]; then
  echo "ripgrep is already installed"
else
  echo "ripgrep is not installed"
  if [ "$system_type" = "Darwin" ]; then
    brew install ripgrep
  else
    if [ -x "$(command -v pacman)" ]; then
      sudo pacman -S ripgrep --noconfirm
    else
      sudo apt install ripgrep -y
    fi
  fi
fi
