#!/bin/sh

system_type=$(uname -s)

if [ type nvim >/dev/null 2>&1 ]; then
  echo "neovim is already installed"
else
  echo "neovim is not installed"
  if [ "$system_type" = "Darwin" ]; then
    brew install neovim
  else
    if [ type pacman >/dev/null 2>&1 ]; then
      sudo pacman -S neovim --noconfirm
    else
      curl -LO https://github.com/neovim/neovim-releases/releases/latest/download/nvim-linux-x86_64.tar.gz
      sudo rm -rf /opt/nvim
      sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
      sudo ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/bin/nvim
      rm nvim-linux-x86_64.tar.gz
    fi
  fi
fi

if [ type starship >/dev/null 2>&1 ]; then
  echo "starship is already installed"
else
  echo "starship is not installed"
  curl -sS https://starship.rs/install.sh | sh -s -- -y
  echo "eval '$(starship init zsh)'" >> ~/.bashrc
fi

if [ type fzf >/dev/null 2>&1 ]; then
  echo "fzf is already installed"
else
  echo "fzf is not installed"
  if [ "$system_type" = "Darwin" ]; then
    brew install fzf
  else
    if [ type pacman >/dev/null 2>&1 ]; then
      sudo pacman -S fzf --noconfirm
    else
      sudo apt install fzf -y
    fi
  fi
fi

if [ type rg >/dev/null 2>&1 ]; then
  echo "ripgrep is already installed"
else
  echo "ripgrep is not installed"
  if [ "$system_type" = "Darwin" ]; then
    brew install ripgrep
  else
    if [ type pacman >/dev/null 2>&1 ]; then
      sudo pacman -S ripgrep --noconfirm
    else
      sudo apt install ripgrep -y
    fi
  fi
fi
